name: Unit tests for rs_openshowvar

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          toolchain: stable

      - name: Run unit tests
        run: cargo test --test unit
